[project]
name = "ldr-design"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.4.5",
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "pandas>=2.3.1",
]

[dependency-groups]
dev = [
    "ruff>=0.12.7",
]
